// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicManagerServer.Data;

#nullable disable

namespace MusicManagerServer.Migrations
{
    [DbContext(typeof(SongDbContext))]
    [Migration("20250428184428_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MusicManagerServer.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Queen",
                            Name = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Led Zeppelin",
                            Name = "Stairway to Heaven"
                        },
                        new
                        {
                            Id = 3,
                            Author = "John Lennon",
                            Name = "Imagine"
                        },
                        new
                        {
                            Id = 4,
                            Author = "The Beatles",
                            Name = "Hey Jude"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nirvana",
                            Name = "Smells Like Teen Spirit"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Train",
                            Name = "Hey, Soul Sister"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
